### PR TITLE
0.2 - Upgrade to Elm 0.17

### PR DESCRIPTION
**Pull request by gdotdesign**
General:
- [x] Migrate all components
- [x] Update dependencies
- [x] Update Kitchensink
- [x] Update scaffolded app 
- [x] Run elm-format on all files
- [x] Write changelog

Modules
- [x] Ext.Color
- [x] Ext.Date
- [x] Ext.Number
- [x] Html.Events.Extra
- [x] Html.Events.Geomtery
- [x] Html.Events.Options

Native Modules
- [x] Browser
- [x] DateTime
- [x] Dom
- [x] Env
- [x] LocalStorage
- [x] Number
- [x] Uid

Ui Modules
- [x] Ui.Helpers.Drag
- [x] Ui.Helpers.Dropdown
- [x] Ui.Helpers.Emitter
- [x] Ui.Helpers.Env
- [x] Ui.Helpers.Intendable
- [x] Ui.Native.Browser
- [x] Ui.Native.Dom
- [x] Ui.Native.LocalStorage
- [x] Ui.Native.Scrolls

Components
- [x] App
- [x] Button
- [x] ButtonGroup
- [x] Calendar
- [x] Checkbox
- [x] Chooser
- [x] ColorPanel
- [x] ColorPicker
- [x] Container
- [x] DatePicker
- [x] DropdownMenu
- [x] Header
- [x] IconButton
- [x] Image
- [x] InplaceInput
- [x] Input
- [x] Layout
- [x] Loader
- [x] Modal
- [x] NotificationCenter
- [x] NumberPad
- [x] NumberRange
- [x] Pager
- [x] Ratings
- [x] SearchInput
- [x] Slider
- [x] Tabs
- [x] Tagger
- [x] Textarea
- [x] Time
- [x] Ui

### CODE REVIEW

**Comment by zdychacek** [comment]
Hi, what's the status of this pull request, when is the ETA of merge?

Thank you.

**Comment by gdotdesign** [comment]
This is basically merge-able, there is one feature that breaks because of the update (the notification center is buggy because of the lack of the key attribute https://groups.google.com/forum/#!searchin/elm-discuss/key$20lazy$20dict/elm-discuss/p-5XSiuv2cI/VgmqxXaoBwAJ)

I'm just waiting on feedback right now, so If everyone here thinks this can go live then I'll merge it :) 
In the mean time this version is installable with the alpha tag `npm install elm-ui@alpha -g`

**Comment by gdotdesign** [comment]
The keys will be added back in 0.17.1 https://groups.google.com/d/msg/elm-dev/vnBfx9DHUuY/gUFoe2wgAwAJ so I'll wait for that with the release

**Comment by gdotdesign** [comment]
Released: https://github.com/gdotdesign/elm-ui/releases/tag/0.2.1

**Pull request merged**
